# Generated by Django 5.1.2 on 2024-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledata',
            name='source',
            field=models.CharField(default='j', max_length=50),
            preserve_default=False,
        ),
    ]
